### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'configs/test1.txt'

### ISSUE THREAD

**Issue by ismailsamatar** [VahidTa/firewall_migration_tool#1]
Hi,

i keep getting this permissionError when i try converting from Paloalto to ASA code 

PermissionError: [Errno 13] Permission denied: 'configs/test1.txt'

**Comment by ismailsamatar** [comment]
Traceback (most recent call last):
  File "/mnt/c/Users/isamatar/Desktop/firewall_migration_tool-main/resources/parser.py", line 22, in main_parser
    output.policy
  File "/mnt/c/Users/isamatar/Desktop/firewall_migration_tool-main/resources/src_vendor/palo/palo_config_coverter.py", line 179, in policy
    palo_policy(self.cfg_file, self.vendor)
  File "/mnt/c/Users/isamatar/Desktop/firewall_migration_tool-main/resources/src_vendor/palo/palo_policy_convert.py", line 53, in palo_policy
    os.remove(f'configs/{file}')
PermissionError: [Errno 13] Permission denied: 'configs/test1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 74, in main
    result = main_parser(action, filename, src_vendor, dst_vendor, acts)
  File "/mnt/c/Users/isamatar/Desktop/firewall_migration_tool-main/resources/parser.py", line 51, in main_parser
    os.remove(f'configs/{cfg}')

**Comment by VahidTa** [comment]
Hi @ismailsamatar ,

Thank you for using this package.

Please verify that you are using root privilege user to run the project. Also, please verify if /config path has write access for your user. Let me know if it helped you or not.

**Comment by ismailsamatar** [comment]
Hi Vahid,

what version of paloalto code is supported in this tool ?

**Comment by VahidTa** [comment]
Hi @ismailsamatar ,

Does your first issue resolved?

I checked it with PanOS 10.0. Do you have any issue? Please share it.

**Comment by ismailsamatar** [comment]
yes but i'm still getting another issue, i'm using panos 8.1

***@***.***:~$ sudo docker exec -it 50a808580825 /bin/bash
***@***.***:/code# cat logs/
.keep app.log
***@***.***:/code# cat logs/app.log
2021-07-27 15:09:27 INFO [app.py:73] Conversion started ...
2021-07-27 15:09:27 INFO [parser.py:21] Policy conversion started ...
2021-07-27 15:09:27 WARNING [parser.py:49] Conversion Failed! Please
re-check file content or Source vendor.
2021-07-27 15:09:27 INFO [parser.py:50]
==================================================
2021-07-27 15:11:28 INFO [app.py:73] Conversion started ...
2021-07-27 15:11:28 INFO [parser.py:21] Policy conversion started ...
2021-07-27 15:11:28 WARNING [parser.py:49] Conversion Failed! Please
re-check file content or Source vendor.
2021-07-27 15:11:28 INFO [parser.py:50]
==================================================
2021-07-27 15:30:18 INFO [app.py:73] Conversion started ...
2021-07-27 15:30:18 INFO [parser.py:21] Policy conversion started ...
2021-07-27 15:30:18 WARNING [parser.py:49] Conversion Failed! Please
re-check file content or Source vendor.
2021-07-27 15:30:18 INFO [parser.py:50]
==================================================

**Comment by VahidTa** [comment]
Please verify that your exported config is based on https://fwmig.readthedocs.io/en/latest/palo.html .

**Comment by VahidTa** [comment]
As first issue resolved and discussion not continued, I will close this issue. Please open new one if there is an issue.
